
// This file has been generated by the GUI designer. Do not modify.
namespace GraphDrawing
{
	public partial class MainWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GraphDrawing.MainWindow
			this.Name = "GraphDrawing.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Graph drawing");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
